import request from '../utils/request'

export const getCourses = params => request.get('/courses', { params })
export const getMyCourses = () => request.get('/courses/mine')
export const getSubjects = () => request.get('/teacher/subjects')
export const getClasses = () => request.get('/teacher/classes')
export const getStudents = () => request.get('/teacher/students')
export const saveCourse = data => request.post('/courses', data)
export const changeCourseStatus = (id, status) => request.post(`/courses/${id}/status/${status}`)
export const deleteCourse = id => request.delete(`/courses/${id}`)
export const getMaterials = courseId => request.get(`/courses/${courseId}/materials`)
export const saveMaterial = data => request.post('/courses/materials', data)
export const deleteMaterial = id => request.delete(`/courses/materials/${id}`)

export const getQuestions = params => request.get('/teacher/questions', { params })
export const getQuestionList = subjectId => request.get('/teacher/questions/list', { params: { subjectId } })
export const getQuestionDetail = id => request.get(`/teacher/questions/${id}`)
export const saveQuestion = data => request.post('/teacher/questions', data)
export const deleteQuestion = id => request.delete(`/teacher/questions/${id}`)
export const getKnowledge = subjectId => request.get('/teacher/knowledge', { params: { subjectId } })
export const saveKnowledge = data => request.post('/teacher/knowledge', data)

export const getHomeworks = params => request.get('/teacher/homeworks', { params })
export const saveHomework = data => request.post('/teacher/homeworks', data)
export const publishHomework = id => request.post(`/teacher/homeworks/${id}/publish`)
export const deleteHomework = id => request.delete(`/teacher/homeworks/${id}`)
export const getSubmits = homeworkId => request.get(`/teacher/homeworks/${homeworkId}/submits`)
export const gradeSubmit = (id, comment) => request.post(`/teacher/submits/${id}/grade`, { comment })
export const getSubmitDetail = id => request.get(`/teacher/submits/${id}`)
export const getKnowledgeAnalysis = homeworkId => request.get(`/teacher/homeworks/${homeworkId}/knowledge-analysis`)
export const getClassOverview = () => request.get('/teacher/analysis/class-overview')
